Base/Application/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    #Doglover
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('alimentos/', views.alimentos, name="alimentos"),
    path('accesorios/', views.accesorios, name="accesorios"),
    path('servicios/', views.servicios, name="servicios"),
    path('fichas/', views.fichas, name="fichas"),
    path('calc/', views.calc, name="calc"),
    path('login_view/', views.login_view, name="login_view"),
    #Crud Usuarios
    path('user_list/', views.user_list, name='user_list'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),  # URL para eliminar usuario
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    #Productos Crud
    path('lista_productos/', views.lista_productos, name='lista_productos'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    #Sesiones
    path("accounts/", include("django.contrib.auth.urls")),
    path('menu/', views.menu, name="menu"),
    path('home', views.home, name='home'),
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    #Login
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup, name='signup'),
    #Carrito
    path('carrito',views.carrito,name="carrito"),
    path('',views.tienda,name="Tienda"),
    path('agregar/<int:producto_id>/',views.agregar_producto, name="Add"),
    path('eliminar/<int:producto_id>/',views.eliminar_producto, name="Del"),
    path('restar/<int:producto_id>/',views.restar_producto, name="Sub"),
    path('limpiar/',views.limpiar_carrito, name="CLS"),
    ]
    

Base/Base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Application.urls')),
]

Base/Application/models.py
from django.db import models
from django.contrib.auth.models import User

class Producto(models.Model):
    TIPO_PRODUCTO_CHOICES = [
        ('accesorio', 'Accesorio'),
        ('alimento', 'Alimento'),
    ]

    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    tipo_producto = models.CharField(max_length=10, choices=TIPO_PRODUCTO_CHOICES)
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nombre
    
class ProductoP(models.Model):
    nombre = models.CharField(max_length=200)
    categoria = models.CharField(max_length=200, default='sin_categoria')
    precio = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.nombre} -> {self.precio}'   

    
class Carrito(models.Model):
    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.cliente.username} - {self.producto.nombre}"
 
    

Base/Application/forms.py
from django import forms
from .models import Producto
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    first_name = forms.CharField(max_length=30, required=True, help_text='Required. Enter your first name.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required. Enter your last name.')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']  # Campos que se pueden editar

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'tipo_producto', 'precio']

class UserEditForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

Base/Application/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Producto, Carrito, ProductoP
from .forms import SignUpForm, UserEditForm, ProductoForm, UserEditForm, CustomPasswordChangeForm

# Links
def carrito(request):
    return render(request, 'Application/carrito.html')

def index(request):
    return render(request, 'Application/index.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index') 
    else:
        form = AuthenticationForm()
    
    return render(request, 'Application/login.html', {'form': form})

def alimentos(request):
    return render(request, 'Application/alimentos.html')

def accesorios(request):
    return render(request, 'Application/accesorios.html')

def servicios(request):
    return render(request, 'Application/servicios.html')

def about(request):
    return render(request, 'Application/about.html')

def fichas(request):
    return render(request, 'Application/fichas.html')

def calc(request):
    return render(request, 'Application/calc.html')

#Sesiones
@login_required
def menu(request):
    request.session["usuario"]="cgarcia"
    usuario=request.session["usuario"]
    context={'usuario':usuario}
    return render(request,'Application/servicios.html', context)

def home(request):
    context={}
    return render(request,'Application/index.html', context)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                
                return redirect('login')
    else:
        form = SignUpForm()
    
    return render(request, 'Application/signup.html', {'form': form})

#Lista de usuarios, Añadir, Borrar y Editar

def user_list(request):
    users = User.objects.all()
    return render(request, 'Application/user_list.html', {'users': users})

def delete_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)  
    if request.method == 'POST':
        user.delete()  
        return redirect('user_list')  
    else:
        return redirect('user_list') 
    
def edit_user(request, user_id):
    user = get_object_or_404(User, pk=user_id) 
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()  
            return redirect('user_list')  
    else:
        form = UserEditForm(instance=user) 
    
    context = {
        'form': form,
        'user_id': user_id,
    }
    return render(request, 'Application/edit_user.html', context)

#PERFIL USUARIO

@login_required
def perfil_usuario(request):
    user = request.user
    context = {
        'nombre': user.first_name,
        'apellido': user.last_name
    }
    return render(request, 'Application/perfil_usuario.html', context)

@login_required
def editar_perfil(request):
    user = request.user
    
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=user)
        password_form = CustomPasswordChangeForm(user, request.POST)

        if 'guardar_cambios' in request.POST:
            if user_form.is_valid():
                user_form.save()
                return redirect('perfil_usuario')

        elif 'cambiar_contrasena' in request.POST:
            if password_form.is_valid():
                password_form.save()
                update_session_auth_hash(request, password_form.user)
                return redirect('perfil_usuario')

    else:
        user_form = UserEditForm(instance=user)
        password_form = CustomPasswordChangeForm(user)

    context = {
        'user_form': user_form,
        'password_form': password_form
    }
    return render(request, 'Application/editar_perfil.html', context)

#TABLA PRODUCTOS

#Mostrar productos
def lista_productos(request):
    productos = Producto.objects.all()
    return render(request, 'Application/lista_productos.html', {'productos': productos})

def agregar_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_productos')
    else:
        form = ProductoForm()
    return render(request, 'Application/agregar_producto.html', {'form': form})

#Carrito

def tienda(request):

    productos = ProductoP.objects.all()
    return render(request,"tienda.html", {'productos':productos})

def agregar_productoP(request, producto_id):
    carrito = Carrito(request)
    producto = ProductoP.objects.get(id=producto_id)
    carrito.agregar(producto)
    return redirect("Tienda")

def eliminar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = ProductoP.objects.get(id=producto_id)
    carrito.eliminar(producto)
    return redirect("Tienda")

def restar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = ProductoP.objects.get(id=producto_id)
    carrito.restar(producto)
    return redirect("Tienda")

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect("Tienda")

Base/Application/templates/Application/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'Application/css/estilos.css'%}"/> <!--Importar estilos de otro archivo--> 
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script> 
    <script src="https://kit.fontawesome.com/165547e65c.js" crossorigin="anonymous"></script> <!--Importando Iconos-->
    <title>Nosotros</title>
</head>
<body background="{%static 'Application/pics/bkgd.png'%}">
    <header>
        <!--Header/Cabecera-->
        <!--Video Contexto: https://www.youtube.com/watch?v=OuoLQiXPitk-->

        <div class ="logo"> 
            <img src="{%static 'Application/pics/logo.png'%}" alt="logo de la pagina">
            <h2 class="nombre-empresa">Dog Lover</h2>
        </div>    
        <nav>
            <ul>
            <li><a href="{%url 'servicios'%}" class="nav-link">Servicios</a></li>
            <li>
                <a>Productos</a>
                <ul class="dropdown">
                <li><a href="{%url 'accesorios'%}" class="nav-link">Accesorios</a></li>
                <li><a href="{%url 'alimentos'%}" class="nav-link">Alimentos</a></li>
                </ul>
            </li>
            <li><a>Nosotros</a></li>
            {% if user.is_authenticated %}
                    <li>
                        <a>{{ user.username }}</a>
                        <ul class="dropdown">
                            {% if user.is_staff %}
                                <li><a href="{% url 'admin:index' %}" class="nav-link">Panel de Admin</a></li>
                                <li><a href="{% url 'fichas' %}" class="nav-link">Revisar Fichas</a></li>
                                <li><a href="{% url 'user_list' %}" class="nav-link">Gestionar Usuarios</a></li>
                                <li><a href="{%url 'lista_productos'%}" class="nav-link">Gestionar Productos</a></li>
                            {% else %}
                                <li><a href="" class="nav-link">Mi Carrito</a></li>
                                <li><a href="{%url 'perfil_usuario'%}" class="nav-link">Mi Perfil</a></li>
                            {% endif %}
                            <li>
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="nav-link">Cerrar Sesion</button>
                                </form>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login_view' %}">Login</a></li>
                {% endif %}
            </ul>   
        </nav>
    </header>
    
    <!--Titulo y Parrafos-->
    <div class ="ttxtbx">
    <h1>Acerca de Nosotros</h1>
    
    <p>Bienvenido a "Dog Lover", nos dedicamos a brindar el mejor servicio para el cuidado y embellecimiento de tu peludo. En nuestra peluquería canina, nos apasiona
        trabajar con perros de todas las razas y tamaños, ofreciendo un ambiente tranquilo y amigable para que se sientan relajados durante su sesión de belleza.
    
    <p>Nuestra visión es convertirnos en un referente en el sector de la peluqueria canina, donde se destaque  nuestro excelente servicio al cliente, nuestra variedad y calidad de los productos, habilidad como equipo para realzar la belleza y bienestar de cada mascota. Queremos un lugar donde las mascotas y sus dueños se sientan como en casa, con amor y cuidado en cada servicio que brindamos.</p>

    <p>Video de nuestro patrocinador:<a href="https://www.youtube.com/watch?v=J4HYF_DFKPU" target="blank">https://www.youtube.com/watch?v=J4HYF_DFKPU</a></p>
    
    <!--Reproductor de video Javascript-->
    <div class="videocaja">
        <div id="player"></div>
    </div>

    <p>Estamos comprometidos en cumplir con todas las expectativas y estandares de cuidado para tu canino. Nos esforzamos por crear un ambiente seguro y acogedor para que tanto tu como tu mascota
        disfruten de la experiencia en nuestra peluquería.</p>
        
    <p>Ven a visitarnos! descubre la mejor experiencia de cuidado y aseo para caninos.</p>
    </div>
   <!--Footer-->
   <footer class="footer">
    <div class="fontainer">
        <div class="row">
            <div class="footer-col">
                <img src="{%static 'Application/pics/logo.png'%}" alt="error">
            </div>
            <div class="footer-col">
                <h3>INTEGRANTES</h3>
                <p>David Segura</p>
                <p>Enzo Toledo</p>
                <p>Claudio Galiano</p>  
            </div>
            <div class="footer-col">
                <h3>SIGUENOS</h3>
                <a href="https://www.facebook.com/Pelucaninadoglover" class="fa fa-facebook" target="blank"></a>
                <a href="https://www.instagram.com/peluqueriacanina_doglover/" class="fa fa-instagram" target="blank"></a>
                <a href="https://twitter.com/" class="fa fa-twitter" target="blank"></a>
            </div>
            <div class="footer-col">
                <h3>CONTACTOS</h3>
                <p>Whatsapp: +56966644433</p>
                <p>Localizacion: Carmen&nbsp;1007, Santiago&nbsp;Centro Chile</p>
            </div>            
        </div>
    </div>
</footer>
<div class="copyright">
<small>&copy; 2024 <b>Dog Lover</b> - Todos los Derechos Reservados.</small>
<script type="text/javascript" src="{%static 'Application/js/functions.js'%}"></script>
</body>
</html>

Base/Application/templates/Application/agregar_producto.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'Application/css/estilos.css'%}"/> <!--Importar estilos de otro archivo--> 
    <title>Agregar Producto</title>
</head>
<body>
    <header>
        <!--Header/Cabecera-->
        <!--Video Contexto: https://www.youtube.com/watch?v=OuoLQiXPitk-->

        <div class ="logo"> 
            <img src="{%static 'Application/pics/logo.png'%}" alt="error">
            <h2 class="nombre-empresa">Dog Lover</h2>
        </div>    
        </div>    
        <nav>
            <ul>
            <li><a href="{% url 'lista_productos'%}" class="nav-link"> > Volver</a></li>    
            </ul>
            </nav>    
    </header>
    <center>
        <h2>Agregar Nuevo Producto</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Producto</button>
    </form>
    </center>
</body>
</html>

Base/Application/templates/Application/alimentos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://code.jquery.com/jquery-3.7.1.js"></script> 
    <link rel="stylesheet" href="{%static 'Application/css/estilos.css'%}"/> <!--Importar estilos de otro archivo--> 
    <script src="https://kit.fontawesome.com/165547e65c.js" crossorigin="anonymous"></script> <!-- Importando Iconos -->
    <title>Alimentos</title>
</head>
<body background="{%static 'Application/pics/bkgd.png'%}">
    <header>
        <!--Header/Cabecera-->
        <!--Video Contexto: https://www.youtube.com/watch?v=OuoLQiXPitk-->

        <div class ="logo"> 
            <img src="{%static 'Application/pics/logo.png'%}" alt="logo de la pagina">
            <h2 class="nombre-empresa">Dog Lover</h2>
        </div>    
        <nav>
            <ul>
            <li><a href="{%url 'servicios'%}" class="nav-link">Servicios</a></li>
            <li>
                <a>Productos</a>
                <ul class="dropdown">
                <li><a href="{%url 'accesorios'%}" class="nav-link">Accesorios</a></li>
                <li><a>Alimentos</a></li>
                </ul>
            </li>
            <li><a href="{%url 'about'%}" class="nav-link">Nosotros</a></li>
			{% if user.is_authenticated %}
                    <li>
                        <a>{{ user.username }}</a>
                        <ul class="dropdown">
                            {% if user.is_staff %}
                                <li><a href="{% url 'admin:index' %}" class="nav-link">Panel de Admin</a></li>
                                <li><a href="{% url 'fichas' %}" class="nav-link">Revisar Fichas</a></li>
                                <li><a href="{% url 'user_list' %}" class="nav-link">Gestionar Usuarios</a></li>
                                <li><a href="{%url 'lista_productos'%}" class="nav-link">Gestionar Productos</a></li>
                            {% else %}
                                <li><a href="" class="nav-link">Mi Carrito</a></li>
                                <li><a href="{%url 'perfil_usuario'%}" class="nav-link">Mi Perfil</a></li>
                            {% endif %}
                            <li>
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="nav-link">Cerrar Sesion</button>
                                </form>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login_view' %}">Login</a></li>
                {% endif %}
            </ul>
            </ul>
        </nav>
    </header>
    
    <!-- Titulo y Parrafos -->
	<center>
        <h1 class="titulo_blanco">Alimentos</h1>
			<div class="text-transparent">
				<p> No sabes cómo calcular la cantidad adecuada de alimento para tu peludo compañero? ¡Descubre la respuesta con nuestra práctica calculadora de porciones!</p>
				<a href="{%url 'calc'%}">>>Haz Click Aqui!<<</a>
				<p>&nbsp;</p>
			</div>
	</center>
<!--Productos(CELDAS)-->          
<div class="container">

	<div class="products-container">
 
	   <div class="product" data-name="p-1"> <!-- ID, funciona en tandem con el script de "Script 2"-->
		  <img src="{%static 'Application/pics/ali1.png'%}" alt="">
		  <h3>Pedigree Cachorro Etapa 2</h3>
		  <div class="price">20,000 CLP</div>
	   </div>
 
	   <div class="product" data-name="p-2">
		  <img src="{%static 'Application/pics/ali2.png'%}" alt="">
		  <h3>Trocitos Pedigree Adulto</h3>
		  <div class="price">3,000 CLP</div>
	   </div>
 
	   <div class="product" data-name="p-3">
		  <img src="{%static 'Application/pics/ali3.png'%}" alt="">
		  <h3>Pedigree Senior Etapa 3</h3>
		  <div class="price">15,000 CLP</div>
	   </div>
 
	   <div class="product" data-name="p-4">
		  <img src="{%static 'Application/pics/ali4.png'%}" alt="">
		  <h3>Filhotes Cachorro Pedigree</h3>
		  <div class="price"> 9,000 CLP</div>
	   </div>
 
	   <div class="product" data-name="p-5">
		  <img src="{%static 'Application/pics/ali5.png'%}" alt="">
		  <h3>Pedigree Cachoro Etapa 1</h3>
		  <div class="price">15,000 CLP</div>
	   </div>
 
	   <div class="product" data-name="p-6">
		  <img src="{%static 'Application/pics/ali6.png'%}" alt="">
		  <h3>Churu INABA</h3>
		  <div class="price">5,000 CLP</div>
	   </div>
	</div>
 </div>
 <!--POP UPS-->
 <div class="products-preview">
 
	<div class="preview" data-target="p-1">  <!-- ID, funciona en tandem con el script de "Script 2"-->
	   <i class="fas fa-times"></i> <!--Boton para cerrar Pop up-->
	   <h3>Pedigree Cachorro Etapa 2</h3>
	   <p>Alimento pedigree para cachorros, Etapa 2.</p>
	   <div class="price">20,000CLP</div>
	   <div class="buttons">
		  <a href="{% url 'alimentos'%}" class="buy">Comprar</a>
	   </div>
	</div>

	<div class="preview" data-target="p-2">
		<i class="fas fa-times"></i> <!--Boton para cerrar Pop up-->
		<h3>Trocitos Pedigree Adulto</h3>
		<p>Alimento pedigree para Caninos Adultos, Etapa 3.</p>
		<div class="price">3,000CLP</div>
		<div class="buttons">
		   <a href="{% url 'alimentos'%}" class="buy">Comprar</a>
		</div>
	 </div>

	 <div class="preview" data-target="p-3">
		<i class="fas fa-times"></i> <!--Boton para cerrar Pop up-->
		<h3>Pedigree Senior Etapa 3 </h3>
		<p>Alimento pedigree para caninos viejos, Etapa 3.</p>
		<div class="price">15,000CLP</div>
		<div class="buttons">
		   <a href="{% url 'alimentos'%}" class="buy">Comprar</a>
		</div>
	 </div>
	 
	 <div class="preview" data-target="p-4">
		<i class="fas fa-times"></i> <!--Boton para cerrar Pop up-->
		<h3>Filhotes Cachorro Pedigree</h3>
		<p>Alimento enlatado pedigree para cachorros.</p>
		<div class="price">9,000CLP</div>
		<div class="buttons">
		   <a href="{% url 'alimentos'%}" class="buy">Comprar</a>
		</div>
	 </div>
 
	 <div class="preview" data-target="p-5">
		<i class="fas fa-times"></i> <!--Boton para cerrar Pop up-->
		<h3>Pedigree Cachorro Etapa 1</h3>
		<p>Alimento pedigree para cachorros jovenes, etapa 1.</p>
		<div class="price">15,000CLP</div>
		<div class="buttons">
		   <a href="{% url 'alimentos'%}" class="buy">Comprar</a>
		</div>
	 </div>

	 <div class="preview" data-target="p-6">
		<i class="fas fa-times"></i> <!--Boton para cerrar Pop up-->
		<h3>Churu INABA</h3>
		<p>Bocadillo para caninos churu.</p>
		<div class="price">15,000CLP</div>
		<div class="buttons">
		   <a href="{% url 'alimentos'%}" class="buy">Comprar</a>
		</div>
	 </div>

 </div>
    <!--Footer-->
    <footer class="footer">
		<div class="fontainer">
			<div class="row">
				<div class="footer-col">
					<img src="{%static 'Application/pics/logo.png'%}" alt="error">
				</div>
				<div class="footer-col">
					<h3>INTEGRANTES</h3>
					<p>David Segura</p>
					<p>Enzo Toledo</p>
					<p>Claudio Galiano</p>  
				</div>
				<div class="footer-col">
					<h3>SIGUENOS</h3>
					<a href="https://www.facebook.com/Pelucaninadoglover" class="fa fa-facebook" target="blank"></a>
                  	<a href="https://www.instagram.com/peluqueriacanina_doglover/" class="fa fa-instagram" target="blank"></a>
                  	<a href="https://twitter.com/" class="fa fa-twitter" target="blank"></a>   
				</div>
				<div class="footer-col">
					<h3>CONTACTOS</h3>
					<p>Whatsapp: +56966644433</p>
					<p>Localizacion: Carmen&nbsp;1007, Santiago&nbsp;Centro Chile</p>
				</div>            
			</div>
		</div>
	</footer>
<div class="copyright">
    <small>&copy; 2024 <b>Dog Lover</b> - Todos los Derechos Reservados.</small>
	<script type="text/javascript" src="{%static 'Application/js/functions.js'%}"></script>
</body>
</html>

Base/Application/templates/Application/edit_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit User</title>
</head>
<body>
    <h2>Edit User</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</body>
</html>

Base/Application/templates/Application/lista_productos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'Application/css/estilos.css'%}"/> <!--Importar estilos de otro archivo--> 
    <title>Lista de Productos</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
    </style>
</head>
<body>
    <header>
        <!--Header/Cabecera-->
        <!--Video Contexto: https://www.youtube.com/watch?v=OuoLQiXPitk-->

        <div class ="logo"> 
            <img src="{%static 'Application/pics/logo.png'%}" alt="error">
            <h2 class="nombre-empresa">Dog Lover</h2>
        </div>    
        </div>    
        <nav>
            <ul>
            <li><a href="{% url 'alimentos'%}" class="nav-link"> > Volver</a></li>    
            </ul>
            </nav>    
        </header>
    <center>
        <h2>Lista de Productos</h2>
    <a href="{% url 'agregar_producto' %}">Añadir Producto</a>
    <br><br>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Tipo de Producto</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
                <td>{{ producto.id }}</td>
                <td>{{ producto.nombre }}</td>
                <td>{{ producto.descripcion }}</td>
                <td>{{ producto.get_tipo_producto_display }}</td>
                <td>${{ producto.precio }}</td>
                <td>

                    <form action="" method="post"> 
                        {% csrf_token %}
                        <button type="submit">Añadir al Carrito</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </center>
</body>
</html>